#!/bin/bash

NAME=ldap-ssp-lam-app

IMAGE=$NAME:1.0

ENV="\
 -e LDAP_URL=ldap://ubox0:389 \
 -e LDAP_BINDDN=cn=admin,dc=salcom,dc=com \
 -e LDAP_BINDPW=admin \
 -e LDAP_BASE=dc=salcom,dc=com \
"

PORTS="-p 127.0.0.1:84:80"

RUN_OPTIONS="--restart=no --add-host=ubox0:192.168.1.51"

docker build --tag $IMAGE -f Dockerfile .

docker stop $NAME

docker rm $NAME

docker run $RUN_OPTIONS $ENV $PORTS --name $NAME -d $IMAGE
